Screen: 
    NavigationLayout:
        ScreenManager:
            Screen:                    
                BoxLayout:
                    orientation:'vertical'
                    MDToolbar:
                        title:"test"
                        elevation:10
                        left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]                 
                    ScreenManager:
                        id: screen_manager
                        Home:
                        CreateScreen:
                        CreateStudent:
                        ManageStudents:
                        ManageUsers:
                        Student_Code:
                        StudentProfile:
                        UserProfile: 
                    
        MDNavigationDrawer:
            id: nav_drawer
            BoxLayout:
                orientation:'vertical'
                Image:
                    source: "logo2.png"
                ScrollView:
                    MDList:
                        OneLineListItem:
                            text: "Utilisateurs"
                            on_release:
                                screen_manager.current = "manage_users"
                                nav_drawer.set_state("close")
                        OneLineListItem:
                            text: "crée un utilisateur"
                            on_release:
                                screen_manager.current = "create"
                                nav_drawer.set_state("close")
                        OneLineListItem:
                            text: "Etudiants"
                            on_release: 
                                screen_manager.current = "manage_students"
                                nav_drawer.set_state("close")
                        OneLineListItem:
                            text: "test button user"
                            on_release: 
                                screen_manager.current = "user_profile"
                                screen_manager.get_screen("user_profile").viewUserProfile()
                                nav_drawer.set_state("close")
                        OneLineListItem:
                            text: "test button stud"
                            on_release:
                                screen_manager.get_screen("student_profile").viewStudProfile() 
                                screen_manager.current = "student_profile"
                                nav_drawer.set_state("close")
        
<Home>:
    name:"home"


<CreateScreen>:
    name:"create"
    BoxLayout:
        orientation: 'vertical'
        MDLabel:
            size_hint:(1,0.5)
            text: "     Nom:"
        MDTextField:
            size_hint:(0.75,0.5)
            pos_hint:{'center_x':0.5}             
            id:nom
        MDLabel:
            size_hint:(1,0.5)
            text: "     Prénom:"
        MDTextField:
            size_hint:(0.75,0.5)
            pos_hint:{'center_x':0.5}   
            id:prenom
        MDLabel:
            text: "     tel:"
            size_hint:(1,0.5)
        MDTextField:
            pos_hint:{'center_x':0.5}    
            id:tel
            size_hint:(0.75,0.5)
        MDLabel:
            text: "     Nbr. d'étudiants:"
            size_hint:(1,0.5)
        MDTextField:
            pos_hint:{'center_x':0.5}  
            size_hint:(0.75,0.5)
            id:nbr
        MDRectangleFlatButton:
            text:"submit"
            pos_hint:{'y':0.5,'center_x':0.5}
            size_hint:(0.5,0.5)
            on_press:
                root.add_user()
                app.help_str.ids.screen_manager.current = 'home'
                

<CreateStudent>:
    name:"create_stud"
    BoxLayout:
        orientation: 'vertical'
        MDLabel:
            text: "     Nom:"
            size_hint:(1,0.5)
        MDTextField:
            size_hint:(0.75,0.5)
            pos_hint:{'center_x':0.5}
            id:stud_nom
        MDLabel:
            text: "     Prénom:"
            size_hint:(1,0.5)
        MDTextField:
            size_hint:(0.75,0.5)
            pos_hint:{'center_x':0.5}
            id:stud_prenom
        MDLabel:
            text: "     tel:"
            size_hint:(1,0.5)
        MDTextField:
            size_hint:(0.75,0.5)
            pos_hint:{'center_x':0.5}
            id:stud_tel
        MDRectangleFlatButton:
            text:"submit"
            pos_hint:{'y':0.5,'center_x':0.5}
            size_hint:(0.5,0.5)
            on_press:
                root.add_student()
                app.help_str.ids.screen_manager.current = 'home'
    
        
<ManageStudents>:
    name:"manage_students"
    BoxLayout:
        orientation:'vertical'

<Student_Code>:
    name:"student_code"
    BoxLayout:
        orientation:'vertical'
        MDGridLayout:
            cols:3
            adaptive_height: True
            adaptive_with: True
            MDRectangleFlatButton:
                text:"Profil"
                on_release:
                    root.viewUserProfile()
                    app.help_str.ids.screen_manager.current = 'user_profile'
                
            MDLabel:
                id: stud_code_title
                size_hint:(0.2,0.2)
                text:""
                halign: 'center'
            MDRectangleFlatButton:
                text:"Ajouté"
                on_press:
                    screen_manager.current = 'create_stud'
                
        BoxLayout:
            orientation:'vertical'
            id: box_layout
    

<ManageUsers>:
    name:"manage_users"
    BoxLayout:
        orientation:'vertical'

<StudentProfile>:
    name:"student_profile"
    BoxLayout:
        orientation:'vertical'
        pos_hint:{'center_x':0.5, 'center_y':0.6}
        Image:
            source: 'image.jpg'
            size_hint: (None,None)
            with:200
            allow_stretch: True
            keep_ratio: True
            pos_hint:{'center_x':0.5,'top':0.8}
        MDGridLayout:
            pos_hint:{'x':0.1,'top':0.8}
            row_force_default:True
            row_default_height: 30
            row_default_with: 100
            cols:2
            adaptive_height: True
            MDLabel:
                text: "Nom: "
                font_size:'20sp'
            MDLabel:
                text: ""
                id:profil_s_nom
                pos_hint:{'left':0.5}
                font_size:'20sp'
            MDLabel:
                text: "Prénom: "
                font_size:'20sp'
            MDLabel:
                text: ""
                id:profil_s_prenom
                font_size:'20sp'
            MDLabel:
                text: "Tel: "
                font_size:'20sp'
            MDLabel:
                text: ""
                id:profil_s_tel
                font_size:'20sp'
            MDLabel:
                text: "Code: "
                font_size:'20sp'
            MDLabel:
                text: ""
                id:profil_s_code
                font_size:'20sp'
            MDLabel:
                text: "Code Parains: "
                font_size:'20sp'
            MDLabel:
                text: ""
                font_size:'20sp'
                id:profil_s_par
            MDLabel:
                font_size:'20sp'
                text: "Nom Parains: "
            MDLabel:
                text: ""
                font_size:'20sp'
                id:profil_s_par_nom
            MDLabel:
                font_size:'20sp'
                text: "Prénom Parains: "
            MDLabel:
                font_size:'20sp'
                text: ""
                id:profil_s_par_prenom
        MDRectangleFlatButton:
            text:"Voir Paraint"
            size:(100,50)
            pos_hint:{'center_x':0.5, 'top':0.5}
            on_press:
                app.help_str.ids.screen_manager.current = "user_profile"
                app.help_str.ids.screen_manager.get_screen("user_profile").viewUserProfile()

<UserProfile>:
    name:"user_profile"
    BoxLayout:
        orientation:'vertical'
        Image:
            source: 'image.jpg'
            size_hint: (None,None)
            with:200
            height:150
            allow_stretch: True
            keep_ratio: True
            pos_hint:{'center_x':0.5,'top':0.8}
        MDGridLayout:
            pos_hint:{'x':0.1,'center_y':0.5}
            row_force_default:True
            row_default_height: 30
            row_default_with: 150
            cols:2
            adaptive_height: True
            MDLabel:
                text: "Nom: "
                font_size:'20sp'
            MDLabel:
                text: ""
                id:profil_u_nom
                font_size:'20sp'
            MDLabel:
                text: "Prénom: "
                font_size:'20sp'
            MDLabel:
                text: ""
                id:profil_u_prenom
                font_size:'20sp'
            MDLabel:
                text: "Tel: "
                font_size:'20sp'
            MDLabel:
                text: ""
                id:profil_u_tel
                font_size:'20sp'
            MDLabel:
                text: "Code: "
                font_size:'20sp'
            MDLabel:
                text: ""
                id:profil_u_code
                font_size:'20sp'
            MDLabel:
                text: "Nbr. d'étudiants: "
                font_size:'20sp'
            MDLabel:
                text: ""
                id:profil_u_nbr
                font_size:'20sp'
        BoxLayout:
            size_hint:(0.75,0.3)
            pos_hint:{'center_x':0.5,'center_y':0.5}
            MDRectangleFlatButton:
                text:"généré icacount"
                on_press:
                    
            MDRectangleFlatButton:
                text:"généré icacard"
                on_press:
                